#!/bin/bash

#SBATCH --job-name="info"
#SBATCH --output="./info.out"
#SBATCH --partition=compute
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH -t 00:00:09

lscpu | tr -d " \r" && numactl --hardware | tr -d " \r"
