#!/bin/bash

#SBATCH --job-name="lscpu"
#SBATCH --output="output/lscpu.%j.%N.out"
#SBATCH --partition=shared
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH -t 00:00:10

ibrun lscpu | tr -d " \r"
