#!/bin/bash

#SBATCH --job-name="numainfo"
#SBATCH --output="/home/mhaseeb/pcdsframe/workspace3/autogen/numainfo.out"
#SBATCH --partition=compute
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH -t 00:00:05

numactl --hardware | tr -d " \r"
