theme: jekyll-theme-slate
title: HiCOPS
description: Accelerated large-scale peptide identification from mass spectrometry data through HPC database peptide search
incremental: true
timezone: America/New_York
page_excerpts: true

# show_downloads: true