theme: jekyll-theme-slate
title: HiCOPS
description: Accelerated database peptide search for large-scale identification of peptides from mass spectrometry (MS/MS) data.
incremental: true
timezone: America/New_York
page_excerpts: true
show_downloads: true