name: build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: |
        mkdir -p build-rel
        mkdir -p build-deb
        mkdir -p build-relwithdeb
    - name: configure
      run: |
        cd build-rel
        CC=$(which gcc) CXX=$(which g++) cmake -DCMAKE_INSTALL_PREFIX=../install-rel -DUSE_MPI=OFF -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=14 ..
        cd ../build-deb
        CC=$(which gcc) CXX=$(which g++) cmake -DCMAKE_INSTALL_PREFIX=../install-deb -DUSE_MPI=OFF -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_STANDARD=14 ..
        cd ../build-relwithdeb
        CC=$(which gcc) CXX=$(which g++) cmake -DCMAKE_INSTALL_PREFIX=../install-relwithdeb -DUSE_MPI=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_STANDARD=14 ..
    - name: build
      run: |
        cd build-rel
        # make install -j 4
        cd ../build-deb
        # make install -j 4
        cd ../build-relwithdeb
        # make install -j 4
