name: HiCOPS C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: mkdir -p build 
    - name: configure
      run:
        working-directory: build
        command: cmake -DCMAKE_INSTALL_PREFIX=../install ..
    - name: build
      run:
        working-directory: build
        command: make
    - name: install
      run:
        working-directory: build
        command: make install
