name: HiCOPS C/C++ CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: setup
      run: mkdir -p build 
    - name: configure
      run: |
        cd build
        cmake -DCMAKE_INSTALL_PREFIX=../install .. -DUSE_OMP=ON
    - name: build
      run: |
        cd build
        make
    - name: install
      run: |
        cd build
        make install
