name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: mkdir -p build
      run: cd build
      run: cmake -DCMAKE_INSTALL_PREFIX=../install ..
    - name: build
      run: make
    - name: install
      run: make install
